# print("this is \\\ double slash")
# print("these are /\/\/\/\ mountains")
# print("he is \t awesome")
# print("\\\" \\n \\t \\\'")
# print("\\\'\\\\\"")
# print("\U0001F602")
x=float(input())
y=float(input())
z=float(input())
print(f"average of three numbers is {(x+y+z)/3}")